services:
  webapi:
    image: brunosallesdev/brunothebotapi:latest
    ports:
      - "80:80"
    depends_on:
      - postgres
  blazor:
    image: brunosallesdev/brunothebotblazor:latest
    ports:
      - "5000:80"
    depends_on:
      - postgres
  postgres:
    image: brunosallesdev/postgres:12.4
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
