services:
  postgres:
    image: brunosallesdev/powerdash-db:latest
    container_name: postgres
    networks:
      - powerdash-network

  brunothebotapi:
    image: brunosallesdev/brunothebot-api:latest
    ports:
      - "80011:8080"
      - "80012:443"
    depends_on:
      - postgres
    container_name: brunothebot-api
    networks:
      - thelaserspace-network

  blazorpowerdash:
    image: brunosallesdev/brunothebotblazor:latest
    container_name: brunothebot-blazor
    ports:
      - "55891:8080"
      - "443:443"
    networks:
      - powerdash-network
    depends_on:
      - brunothebotapi
      - postgres

  nginx:
    image: brunosallesdev/powerdash-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    networks:
      - powerdash-network

networks:
  powerdash-network:
  thelaserspace-network:

volumes:
  nginx-config:
    driver: local
