services:
  brunothebot-api:
    ports:
    - "50401:8080"
    - "50402:443"
    image: brunosallesdev/brunothebotapi:latest
    container_name: brunothebot-api
    networks:
      - brunothebot-network

  brunothebot-blazor:
    ports:
    - "50403:8080"
    - "50404:443"
    image: brunosallesdev/brunothebotblazor:latest
    container_name: brunothebot-blazor
    networks:
      - brunothebot-network  

  brunothebot-postgres:
    image: postgres:latest
    container_name: brunothebot-postgres
    environment:
       POSTGRES_PASSWORD: "@pyramid2050!"
       POSTGRES_USER: brunothebotuser
       POSTGRES_DB: BrunoTheBotDB
    networks:
      - brunothebot-network

  nginx:
    image: brunosallesdev/powerdash-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    networks:
      - thelaserspace-network
      - brunothebot-network

networks:
  thelaserspace-network:
    name: thelaserspace-network
  brunothebot-network:
    name: brunothebot-network