services:
  quiztleapi:
    ports:
      - "5041:8080"
      - "5042:443"
    image: brunosallesdev/quiztleapi:latest
    container_name: quiztleapi
    volumes:
      - pdf-bucket-volume:/bucket:rw
      - c:/bucket:/bucket:rw
    environment:
      - PROD_FLASK_API_URL=${PROD_FLASK_API_URL}
      - PROD_POSTGRES_CONNECTION_STRING=${PROD_POSTGRES_CONNECTION_STRING}
      - PDF_DIRECTORY=/bucket
      - IHOST_TIME=${IHOST_TIME}
      - IS_IHOST_ACTIVE=${IS_IHOST_ACTIVE}
      - NGROK_ENDPOINT=${NGROK_ENDPOINT}
    networks:
      - quiztle-network

  quiztleblazor:
    ports:
      - "5001:8080"
      - "5002:443"
    image: brunosallesdev/quiztleblazor:latest
    container_name: quiztleblazor
    environment:
      - PROD_POSTGRES_CONNECTION_STRING=${PROD_POSTGRES_CONNECTION_STRING}
      - PROD_API_URL=${PROD_API_URL}
      - PROD_FLASK_API_URL=${PROD_FLASK_API_URL}
    networks:
      - quiztle-network

  # nginx:
  #   image: brunosallesdev/nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - C:/Users/bsall/source/repos/Quiztle/Quiztle.API/_nginx:/etc/nginx/conf.d
  #     - C:/Users/bsall/source/repos/Quiztle/Quiztle.Blazor/Quiztle.Blazor/_nginx:/etc/nginx/conf.d
  #   networks:
  #     - quiztle-network
  #     - thelaserspace-network
  #   depends_on:
  #     - quiztleapi
  #     - quiztleblazor

  thelaserspace:
    image: brunosallesdev/thelaserspace2024:latest
    ports:
      - "5044:8080"
      - "5045:443"
    container_name: thelaserspace
    networks:
      - thelaserspace-network

  quiztle-postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    container_name: quiztle-postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - quiztle-network
    volumes:
      - quiztle-postgres-data:/var/lib/postgresql/data

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - quiztle-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - quiztle-network
  
  # pdf-api:
  #   build: .  
  #   image: brunosallesdev/quiztle-flask-pdfscanner:latest
  #   container_name: quiztle-flask-pdfscanner
  #   ports:
  #     - "5090:5000"
  #   volumes:
  #     -  pdf-bucket-volume:/bucket/
  #   environment:
  #     BUCKET_PATH: ${BUCKET_PATH}
  #     OUTPUT_FILES: ${OUTPUT_FILES}
  #     PARTIAL_OUTPUT_RATE: ${PARTIAL_OUTPUT_RATE}
  #   networks:
  #     - quiztle-network


volumes:
  nginx-conf-d-volume:
  portainer_data:
  quiztle-postgres-data:
  pdf_input_volume:
  output_volume:
  pdf-bucket-volume:
    driver: local
    driver_opts:
      type: none
      device: c:/bucket
      o: bind

networks:
  quiztle-network:
    name: quiztle-network
    driver: bridge
  thelaserspace-network:
    name: thelaserspace-network
